### ISSUE TITLE
Support other distros as docker base image

### ISSUE THREAD

**Issue by ahmadalli** [grafana/pdc-agent#124]
We've recently faced some issues with the alpine base image regards DNS resolution. In our case we were using `hostAliases` with a long list of hosts which resulted in a single line entry in `/etc/hosts` in the container which seems to be not supported in musl since later entries on that line in the hosts file were ignored by other binaries including ping, wget, and pdc itself. From my tests all hosts up to the 512th character of that line were loaded and the reset were ignored.

We had something like this on our hosts file:

```
127.0.0.1 host1 host2 host3 host4 host5 host6 host7 host8 host9 host10 host11 host12 host13 host14 host15 host16 host17 host18 host19 host20 host21 host22 host23 host24 host25 host26 host27 host28 host29 host30 host31 host32 host33 host34 host35 host36 host37 host38 host39 host40 host41 host42 host43 host44 host45 host46 host47 host48 host49 host50 host51 host52 host53 host54 host55 host56 host57 host58 host59 host60 host61 host62 host63 host64 host65 host66 host67 host68 host69 host70 host71 host72 host73 host74 host75 host76 host77 host78 host79 host80 host81 host82 host83 host84 host85 host86 host87 host88 host89 host90 host91 host92 host93 host94 host95 host96 host97 host98 host99 host100 host101 host102
```

and `ping host73` would work perfectly while `ping host74` and other hosts after that would fail with `bad address` error.

We ended up creating another image for PDC from another distro which fixed this issue but since kubernetes is your recommended way of deploying PDC agent, it'd be great if you could support another distro as docker base image to prevent such issues from happening.

**Comment by dafydd-t** [comment]
Hi @ahmadalli , I'm afraid we won't be releasing Docker images built from a base image other than `alpine` for the forseeable future.
