### ISSUE TITLE
make more ssh flags overrideable

### ISSUE THREAD

**Issue by dafydd-t** [grafana/pdc-agent#20]
Currently, we pass a default verbosity flag and some `-o` flags when invoking the `ssh` command in the agent ([link to defaults](https://github.com/grafana/pdc-agent/blob/main/pkg/ssh/ssh.go#L151-L154)). Users may want to change these defaults, and that is not possible at the moment.

- `-o` flags: from  [ssh_config](https://www.man7.org/linux/man-pages/man5/ssh_config.5.html): `For each parameter, the first obtained value will be used.`. Therefore if the user tries to change one of the default `-o` flags we set, it will be ignored.
- `-v`: we set `-vv`. If the user tries to change this to e.g. `-v`, the additional `v` increases the verbosity (it is additive!).

We should make these flags behave in a more obvious way.

I do not think we should allow the other defaults to be overriden.

**Comment by Hronom** [comment]
It's crazy mess, when you set:
```
            - '-ssh-key-file'
            - /home/pdc/.ssh/grafana_pdc_v3
```
it's increase log level to debug.

When do you plan to fix this?

**Comment by Hronom** [comment]
Basically I cannot set together:
```
            - '-ssh-key-file'
            - /home/pdc/.ssh/grafana_pdc_v4
            - '-log-level'
            - '0'
```
it goes in infinite loop with error:
```
level=error caller=ssh.go:122 msg="ssh client exited. restarting"level=info caller=keymanager.go:52 msg="starting key manager"level=info caller=keymanager.go:165 msg="found existing valid certificate"level=info caller=keymanager.go:178 msg="found valid grafana_pdc_known_hosts"
```
Its very bad implementation

**Comment by dafydd-t** [comment]
@Hronom there is indeed an issue when `-log-level` is set to 0, which should be fixed with https://github.com/grafana/pdc-agent/pull/33.

otherwise i'd check your formatting, I've been able to run with both those config items set together.

**Comment by dafydd-t** [comment]
We have https://github.com/grafana/pdc-agent/issues/51 to tidy up log level flags, so I think this can be closed now.
