### ISSUE TITLE
Building ARM containers

### ISSUE THREAD

**Issue by tsrats** [grafana/pdc-agent#47]
Hello! I was looking to use the Grafana PDC Agent in my Kubernetes cluster, so I followed the direction on Grafana Cloud, only to realise that the Docker images referenced to are x86 only. Would it be possible to build ARM/ARM64 images as well for this?

Thanks!

**Comment by stevef1uk** [comment]
This is actually very easy to do yourself. All you need to do is edit the .goreleaser.yaml file and change amd64 to arm64
Then follow their build instructions.
For a while I will leave my built image on DockerHub if you need one: seahope/grafana-pdc-agent
Regards

**Comment by tsrats** [comment]
> This is actually very easy to do yourself. All you need to do is edit the .goreleaser.yaml file and change amd64 to arm64 Then follow their build instructions. For a while I will leave my built image on DockerHub if you need one: seahope/grafana-pdc-agent Regards

Thank you!

**Comment by Viper3489753489** [comment]
Just dropping a comment for updates. 

Would be ideal to get official arm support that gets updated with new versions instead of having to rebuild the image

**Comment by tsrats** [comment]
Agree with @Viper3489753489, while I was able to build my own container, it was not trivial to do so as someone who has never built Go applications before.

**Comment by dafydd-t** [comment]
Since v0.0.27, the docker image is multi-platoform, also supporting linux/arm64 👍
