### ISSUE TITLE
How to set multiple PermitRemoteOpen hosts?

### ISSUE THREAD

**Issue by sdgluck** [grafana/pdc-agent#68]
I can't figure out by the PDC agent or SSH docs how to specify multiple permitted SSH remote targets?

I have tried the following (as commands to an ECS task running the agent):

```
"-log.level",
"debug",
"-token",  "<redacted>",
"-cluster",
"prod-eu-west-0",
"-gcloud-hosted-grafana-id",
"<redacted>",
"-ssh-flag",
"-o PermitRemoteOpen=<host1>",
"-ssh-flag",
"-o PermitRemoteOpen=<host2>"
```

But the agent logs tell me it parses the flags as follows, indicating only the second PermitRemoteOpen option is applied:

```
parsed flags: [
	-i /home/pdc/.ssh/grafana_pdc <redacted>@private-datasource-connect-prod-eu-west-0.grafana.net
	-p 22
	-R 0
	-o CertificateFile=/home/pdc/.ssh/grafana_pdc-cert.pub
	-o ConnectTimeout=1
	-o PermitRemoteOpen=<host2>
	-o ServerAliveInterval=15
	-o UserKnownHostsFile=/home/pdc/.ssh/grafana_pdc_known_hosts
	-vvv
]
```

I also tried the following:

```
"-o PermitRemoteOpen=<host1>,<host2>"
```

And the flag is parsed as-is. However, no luck with this either.

Any help would be much appreciated. Thank you in advance.

**Comment by caleblloyd** [comment]
It appears [from this test](https://github.com/grafana/pdc-agent/blob/main/pkg/ssh/ssh_test.go#L178) that space-separating a single `-o PermitRemoteOpen` option works

I am having luck using that with version `0.0.25`

**Comment by dafydd-t** [comment]
From the ssh_config docs for the `PermitRemoteOpen` option:

> Multiple forwards may be specified by separating them with whitespace.

As @caleblloyd mentioned, this will work here too. Please reopen this if you have any issues!
